# Generated by Django 5.1.2 on 2024-10-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_members_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='lnane',
            new_name='lname',
        ),
    ]
